name: Run Automation

on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
    - name: Run script
      run: python automation_script.py
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: automation-logs
        path: script.log
    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: youtube-screenshot
        path: youtube_screenshot.png
