name: Selenium Test with Profile

on: [push]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        sudo apt-get install -y unzip

    - name: Setup Chrome Profile
      run: |
        mkdir -p ~/.config/google-chrome/Profile\ 1
        unzip ChromeProfile_ultra.zip -d ~/.config/google-chrome/
        chmod -R 755 ~/.config/google-chrome

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        LATEST=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        google-chrome --version
        chromedriver --version

    - name: Run Selenium Test
      run: |
        python -c "
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        import os
        
        options = Options()
        options.add_argument('--user-data-dir=' + os.path.expanduser('~') + '/.config/google-chrome')
        options.add_argument('--profile-directory=Profile 1')
        options.add_argument('--headless=new')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--disable-gpu')
        options.add_argument('--remote-debugging-port=9222')
        options.add_argument('--window-size=1920,1080')
        
        try:
            driver = webdriver.Chrome(options=options)
            print('Navigating to YouTube...')
            driver.get('https://www.youtube.com')
            print('Current URL:', driver.current_url)
            print('Page title:', driver.title)
            assert 'YouTube' in driver.title
            print('Test passed!')
            driver.quit()
        except Exception as e:
            print('Test failed:', str(e))
            if 'driver' in locals():
                driver.quit()
            raise
        "
